#!/bin/bash
code --install-extension donjayamanne.python-extension-pack
code --install-extension esbenp.prettier-vscode
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension h5web.vscode-h5web
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension ritwickdey.LiveServer
code --install-extension ms-toolsai.jupyter
code --install-extension AdamViola.parquet-explorer
code --install-extension ms-python.vscode-pylance
code --install-extension qwtel.sqlite-viewer
code --install-extension eamodio.gitlens
code --install-extension KevinRose.vsc-python-indent
code --install-extension oderwat.indent-rainbow
code --install-extension Iterative.dvc
code --install-extension REditorSupport.r
code --install-extension RDebugger.r-debugger
code --install-extension julialang.language-julia
code --install-extension cameronbieganek.julia-color-themes
code --install-extension vscode-icons-team.vscode-icons